### ISSUE TITLE
Tratar arquivos

### ISSUE THREAD

**Issue by felipemelchior** [homdreen/Web-Server-with-Protobuf#4]
Entretanto, o cliente nao permite tratar/salvar os arquivos de saida, o que eh ruim.

**Comment by felipemelchior** [comment]
O cliente deveria poder permitir que eu salvasse o arquivo transferido do servidor em um arquivo local.

**Comment by felipemelchior** [comment]
Criei uma versão inicial... Todo Get gera um arquivo com a mesma url no cliente... Está ruim ainda, deveria ser possível escolher onde salvar esse arquivo, talvez um parametro ?

**Comment by wesferr** [comment]
uma pasta output a onde todos os gets serão salvos não seria mais fácil?

**Comment by wesferr** [comment]
esta quebrado, quando a pessoa passa o caminho do arquivo(não só o nome) ele tenta gravar em um caminho no servidor(se não existir ele da erro)
